[package]
name = "meplang"
version = "0.1.3"
edition = "2021"

[dependencies]
primitive-types = "0.12.1"
pest = "2.6"
pest_derive = "2.6"
bytes = "1.4.0"
hex = "0.4.3"
log = "0.4"
env_logger = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.5"
