[package]
name = "meplang"
version = "0.1.0"
edition = "2021"

[dependencies]
primitive-types = "0.12.1"
pest = "2.5.3"
pest_derive = "2.5.3"
bytes = "1.3.0"
hex = "0.4.3"
log = "0.4.17"
env_logger = { version = "0.10.0"  }