unstable_features = true
edition = "2021"
hex_literal_case = "Lower"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 120
imports_granularity = "Module"
group_imports = "StdExternalCrate"
newline_style = "Unix"
blank_lines_upper_bound = 1
